### ISSUE TITLE
Better defaulting of namespace

### ISSUE THREAD

**Issue by jglick** [jenkins-x/ext-jacoco#51]
Currently the environment variable `TEAM_NAMESPACE` is read to determine which namespace should be watched for `pipelineactivities`, defaulting to `jx`, and the old extension install script expect to set this in turn on the chart via some `EXT_TEAM_NAMESPACE` variable. I expect that this logic needs to be replaced by something which just reads `/var/run/secrets/kubernetes.io/serviceaccount/namespace` ([discussion](https://stackoverflow.com/q/53283347/12916)).

**Comment by hferentschik** [comment]
>  I expect that this logic needs to be replaced by something which just reads /var/run/secrets/kubernetes.io/serviceaccount/namespace

Can you elaborate on this? Is it not enough to have the ability to specify the namespace duing `jx add app -e teamNamespace=foo`?

**Comment by jglick** [comment]
> Is it not enough to have the ability to specify the namespace duing `jx add app -e teamNamespace=foo`?

Well that could be made to work of course but then the onus is on the user to know to do this and not mistype the namespace etc. Better to have the app itself operate inside its own namespace automatically.

**Comment by hferentschik** [comment]
> Well that could be made to work of course but then the onus is on the user to know to do this and not mistype the namespace etc. Better to have the app itself operate inside its own namespace automatically.

Hmm, fair enough.  `jx add app` has already a `namespace` option (defaulting to jx). This makes `-e teamNamespace=foo` even more questionable. Assuming that the --namespace option is implemented correctly, one would indeed expect that the app automatically watches this namespace.

I don't want to depend on something like reading `/var/run/secrets/kubernetes.io/serviceaccount/namespace`, though, since it would break the ability to  run the application easily locally.

**Comment by jglick** [comment]
> it would break the ability to run the application easily locally

If that is a real requirement, I would suggest just falling back to `jx`.

**Comment by hferentschik** [comment]
> If that is a real requirement

I think imo is super important for development.

> I would suggest just falling back to jx.

That's a possibility.

BTW, is `/var/run/secrets/kubernetes.io/serviceaccount/namespace` really something one can rely on?

**Comment by deanesmith** [comment]
Based on discussion, looking at helm namespacing if something exists already.  The question is, does the namespace where an app is installed mean the same namespace that it monitors/does-work.

**Comment by hferentschik** [comment]
The Downward API might be the solution https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#the-downward-api

**Comment by jglick** [comment]
> is `/var/run/secrets/kubernetes.io/serviceaccount/namespace` really something one can rely on?

Yes this is the official way to find the namespace associated with your service account, if you have one. K8s clients will read it under certain circumstances.

**Comment by jglick** [comment]
> does the namespace where an app is installed mean the same namespace that it monitors/does-work

Presumably not for every conceivable app, but I think this would be true for all operators, including apps like this one which translate parts of `pipelineactivities` into `facts`.

**Comment by hferentschik** [comment]
Merged by pr #127
