### ISSUE TITLE
Retry updating pipeline CRDs

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/ext-jacoco#58]
Backoff and retry on updating pipeline activity CRD (in case of contention). 

The code should attempt to align the retry strategy used in jx - see https://github.com/jenkins-x/jx/blob/0666a6bc0a80eacdb0820d0b25116ed1b2d4f814/pkg/kube/crds.go#L619

**Comment by jglick** [comment]
There was some discussion with @pmuir, @davidcurrie, et al. about introducing some sort of abstraction layer (or even shared `Deployment`) for apps which do the usual `Attachment` → `Fact` conversion, perhaps via [Metacontroller](https://metacontroller.app/) or the like. We would not want every app with five lines of “business logic” to have to deal with this sort of subtlety.

**Comment by hferentschik** [comment]
> There was some discussion with @pmuir, @davidcurrie, et al. about introducing some sort of abstraction layer (or even shared Deployment) for apps which do the usual Attachment → Fact conversion, perhaps via Metacontroller or the like. 

Anything concrete yet? The question is how can a metacontroller gurnatee that the changes get applied correctly and how would a client, aka the app know that the changes got applied? Is this supposed to be syncronous or asynchronos? 

I am also wondering how much effort one should put into it. AFAIU currently build/app results are registered in CRDs, however this does not scale. I would image that this will change  in the near future.
For that reason I was more thinking putting something into the app code directly. 

There are probably several ways on how this could be shared in the long term. Either by a dedicated appl ibrary which can be imported or by having a app quickstart which contains some appropriate helpers classes. Both approachtes have their pro and cons. For now I thought to just improve on the retry logic and try to alingn it with jx. WDYT?

> We would not want every app with five lines of “business logic” to have to deal with this sort of subtlety.

Sure.

**Comment by hferentschik** [comment]
See also https://stackoverflow.com/questions/52565131/can-i-store-my-application-data-in-kubernetes-configuration-resources

**Comment by hferentschik** [comment]
Merged via PR #91
