### ISSUE TITLE
Delete service from Helm chart

### ISSUE THREAD

**Issue by jglick** [jenkins-x/ext-jacoco#62]
As an app which just acts as a controller, there is no reason to have a `Service`, much less ingress for that service.

**Comment by hferentschik** [comment]
We definitely don't need the ingress. I guess the service is there to be able to define a health check. The code actually spins of an HTTP server. My guess is purely in order to be able to define health and liveliness checks. 

Not sure whether this is a good practice or not. Is there an advantage to use a dummy HTTP server over running an in container command for these checks. 

@jglick @rawlingsj Do we have any best practices around this?

**Comment by jglick** [comment]
> the service is there to be able to define a health check

You can have an (HTTP) health check with no `Service`, right? The `Deployment` would use it to decide whether or not the pod is responsive, without actually exposing that port to anything else.

> Is there an advantage to use a dummy HTTP server over running an in container command for these checks.

You mean [this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-command). I guess the HTTP health check simply ensures that the Go process is somehow running. It does not, however, directly check the health of the operator thread (`actController.Run`). Maybe `cache.NewInformer` can be given some argument to touch a liveness file every minute or so?

**Comment by hferentschik** [comment]
> You can have an (HTTP) health check with no `Service`, right? The `Deployment` would use it to decide whether or not the pod is responsive, without actually exposing that port to anything else.

I guess

> You mean [this](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#define-a-liveness-command). 

Right. Some sort of in container command. It might also not be more than checking whether the process is still running, just not via HTTP. 

> I guess the HTTP health check simply ensures that the Go process is somehow running.

Right. 

> Maybe `cache.NewInformer` can be given some argument to touch a liveness file every minute or so?

Right, if one would like to implement proper liveliness checks one needs to somehow be able to verify that we are properly processing incoming changes.

**Comment by jglick** [comment]
> not be more than checking whether the process is still running

This would not detect a frozen process, though. (I think if the process, as PID 1, actually _exits_ that would be interpreted as a pod failure regardless of any liveness checks.)

**Comment by hferentschik** [comment]
> This would not detect a frozen process, though. 

True. 

> (I think if the process, as PID 1, actually _exits_ that would be interpreted as a pod failure regardless of any liveness checks.)

Sure, if the main process dies, the pod is considered as failed anyways. Do we gain anything with the current dummy HTTP server approach? Unless we integrate some proper checks within the server, it feels like one might as well remove it and rely purely on the implicit process exist check. Less is more.

**Comment by jglick** [comment]
> Unless we integrate some proper checks within the server, it feels like one might as well remove it and rely purely on the implicit process exist check. Less is more.

Makes sense to me.

**Comment by hferentschik** [comment]
merged via pull request #117
