### ISSUE TITLE
Changelog created by release is broken

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/ext-jacoco#68]
On each merge to master a new release is created, for example - https://github.com/jenkins-x-apps/jx-app-jacoco/releases/tag/v0.0.85.

The generated changelog should only contain the changes between the two releases, but currently, it seems all changes from project creation are included. 

This could be a problem with `jx step changelog`. Either there is bug or it is used wrongly.

**Comment by hferentschik** [comment]
@jstrachan @rawlingsj - what's the state of `jx step changelog`. It seems completely broken, at least for this repo.

There is https://github.com/jenkins-x/jx/issues/1543 which indicates other problems with the changelog step.

**Comment by jstrachan** [comment]
yeah - I think there are issues with `jx step changelog` in terms of which tags/shas it's using to query for the changelog. 

Fancy taking a look? ;) would be awesome to fix it!

**Comment by hferentschik** [comment]
> yeah - I think there are issues with `jx step changelog` in terms of which tags/shas it's using to query for the changelog.

Makes sense.

> Fancy taking a look? ;) would be awesome to fix it!

I'll take a look. Sounds interesting and I would love to get this fixed.
