### ISSUE TITLE
Allow for proper shutdown of app

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/ext-jacoco#72]
The go routine channel handling, in particular, the usage of the stop channel, does not allow for a clean shutdown of the container/app.

A top level stop channel should be created and used and passed to the go sub routines. Then an event handler for the various shutdown signals should be registered and used to allow a clean shutdown.

**Comment by fiunchinho** [comment]
Maybe helpful: [this is how we did it for the action-controller](https://github.com/cloudbees/action-controller/blob/610d59aeeb9fb46f3454df82e8ce8d37a917ab2c/pkg/cmd/main.go#L26).

**Comment by hferentschik** [comment]
> Maybe helpful: [this is how we did it for the action-controller](https://github.com/cloudbees/action-controller/blob/610d59aeeb9fb46f3454df82e8ce8d37a917ab2c/pkg/cmd/main.go#L26).

Looks promising. I am not familiar with this particular helper/library, but judging by my brief look, it seems to address what I mean. I have hand-rolled this a few times, but I for sure will have a look at this. Thanks for the heads up.

**Comment by hferentschik** [comment]
Merged via pull request #96
