### ISSUE TITLE
Use 'jx step stash' in documentation for this app

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/ext-jacoco#74]
The readme refers to `jx step collect` in the `Jenkinsfile` as a required step for configuring the app. _collect_ is really just a command alias for _stash_ which I think is much more self-explanatory. I think we should use stash.

Maybe we should also make the implicit git flags in this command explicit, mainly to make it easier for the user to connect the dots.

**Comment by jglick** [comment]
I presume `stash` is preferred both for parity with `unstash`, and to create an analogy to the [Jenkins pipeline step of the same name](https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#stash-stash-some-files-to-be-used-later-in-the-build).

**Comment by hferentschik** [comment]
Merged via PR #81
