### ISSUE TITLE
Add Jacoco App to the Jenkins X Version Stream

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/ext-jacoco#82]
Ensure that the Jacoco app is stable with the latest Jenkins X platform versions.

After promoting the app, submit a PR to https://github.com/jenkins-x/jenkins-x-versions with the latest version. This will then kick off a BDD test run. If the test run is a success the version stream will be updated to point to the latest version of the Jacoco app. 
 
Please see [Version Streams](https://jenkins-x.io/architecture/version-stream/) for further details.

**Comment by hferentschik** [comment]
Sounds reasonable. Personally, I don't think that we need to promote each merge to master, but rather when you explicitly create a release tag. That's a different story though. Once promotion occurs it makes sense to create the pull request into jenkins-x-versions.

**Comment by hferentschik** [comment]
Re-opening the issue to sort out a mistake

**Comment by hferentschik** [comment]
Merged via pull request #93
