### ISSUE TITLE
Jacoco App is not registered under apps.jenkins.io CRD

### ISSUE THREAD

**Issue by daveconde** [jenkins-x/ext-jacoco#83]
At the moment `kubectl get apps` does not list the Jacoco App. This is because there is no associated resource in the helm template for the app.

We have 2 options here:

1) Add a resource template [here](https://github.com/jenkins-x-apps/jx-app-jacoco/tree/master/charts/jx-app-jacoco/templates) similar to how some of the other Apps work.
2) Find a way to auto generate an App Resource definition.

**Comment by hferentschik** [comment]
I would think the easiest way, for now, would be to add it here, right? Also, we discussed to create an app-quickstart. The quickstart would include the _app.yaml_ as well, so there would be nothing to do for an app developer. Also, there is nothing which needs hand editing, right?
